version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
   
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  logs:
